/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as EventsEventIdImport } from './routes/events/$eventId'
import { Route as EEventIdImport } from './routes/e.$eventId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EventsEventIdRoute = EventsEventIdImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRoute,
} as any)

const EEventIdRoute = EEventIdImport.update({
  id: '/e/$eventId',
  path: '/e/$eventId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/e/$eventId': {
      id: '/e/$eventId'
      path: '/e/$eventId'
      fullPath: '/e/$eventId'
      preLoaderRoute: typeof EEventIdImport
      parentRoute: typeof rootRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/e/$eventId': typeof EEventIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/e/$eventId': typeof EEventIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/e/$eventId': typeof EEventIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/e/$eventId' | '/events/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/e/$eventId' | '/events/$eventId'
  id: '__root__' | '/' | '/e/$eventId' | '/events/$eventId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EEventIdRoute: typeof EEventIdRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EEventIdRoute: EEventIdRoute,
  EventsEventIdRoute: EventsEventIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/e/$eventId",
        "/events/$eventId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/e/$eventId": {
      "filePath": "e.$eventId.tsx"
    },
    "/events/$eventId": {
      "filePath": "events/$eventId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
